//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        public int MaHang { get; set; }
        public string Ten { get; set; }
        public string NhaSanXuat { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string DonViTinh { get; set; }
    }
}
